### ISSUE TITLE
请问这个是不是不支持play版微信呢？

### ISSUE THREAD

**Issue by seraph758** [Mingyueyixi/MaskWechat#10]
从发布到现在每次更新都试了，就一个弹出要我去配置，然后点进用户又没有弹出id
![Screenshot_2023-01-30-17-47-09-24_e39d2c7de19156b0683cd93e8735f348](https://user-images.githubusercontent.com/10000026/215655867-0bc9d0a4-fc40-4d85-a470-328d29dbd048.jpg)

**Comment by Mingyueyixi** [comment]
@seraph758  看文档额。仅支持8.0.22/8.0.32，arm64
