### ISSUE TITLE
关于聊天记录隐藏的bug

### ISSUE THREAD

**Issue by eosed** [Mingyueyixi/MaskWechat#13]
虽然聊天页面可以隐藏聊天记录，但是查找聊天记录里面还是能搜索聊天记录，还能按日期查看聊天记录，也能查看交易记录，图片视频等。

**Comment by Mingyueyixi** [comment]
@eosed  也并不算bug，因为一开始并不打算做这个功能。1.7添加这个功能，也只是临时加，未来微信新版很可能不再适配
