### ISSUE TITLE
 临时解除隐藏无效

### ISSUE THREAD

**Issue by ZhouSong0** [Mingyueyixi/MaskWechat#25]
设置的是在150ms内，连续点击5次，然后在空白聊天记录上点击不论多少次都无效

**Comment by Mingyueyixi** [comment]
@Steven7920 
请参考对比你的手速：https://github.com/Mingyueyixi/MaskWechat/issues/1#issuecomment-1407652912
另外，5次不是第五次解开，而是第6次。
