### ISSUE TITLE
谷歌版wechat

### ISSUE THREAD

**Issue by Drz-Drz** [Mingyueyixi/MaskWechat#26]
你好，能对谷歌版微信进行适配吗，谷歌版的微信比较纯净，没有杂七杂八的广告，用起来挺方便的，大佬辛苦了

**Comment by Mingyueyixi** [comment]
不打算进行适配。如主页所诉，作者没有时间=穷，还有就是谷歌版本并非主流版本的原因

**Comment by clupusgao** [comment]
作者再考虑考虑谷歌版呗，能玩模块的人有一定搞机基础，大部分有能力下载谷歌版微信，也喜欢谷歌版微信的纯净

**Comment by Mingyueyixi** [comment]
@mislock 大胸弟已经适配
