### ISSUE TITLE
是否能静默对方发消息

### ISSUE THREAD

**Issue by readme2gh** [Mingyueyixi/MaskWechat#28]
是否能静默对方发消息，不在聊天列表展示．
目前虽然看不到聊天记录，但是发消息会在列表头部展示．

**Comment by Mingyueyixi** [comment]
这个东西，你或许需要考虑加入黑名单或者来消息不显示。作者暂时不会处理。因为需要知道新消息

**Comment by readme2gh** [comment]
拉黑，那隐藏那就没意义．对方发消息聊天列表在最顶部，这样隐藏等于此地无银三百两

**Comment by Mingyueyixi** [comment]
那你可能需要密友之类的模块。
（1）这个模块，现在不会隐藏这个东西
（2）模块一开始核心功能就是只隐藏聊天记录。其他的隐藏都是后面加的功能，并不是一定要支持的
（3）为什么这样处理？因为隐藏实际上是不能够真的保证隐私的。只要同时登陆电脑版，或者仔细检查，肯定会暴露。所以，这只是权宜之计。

**Comment by Mingyueyixi** [comment]
2.1新增会话id替换功能（变脸模式）。使用后，将默认把隐藏用户显示为订阅号，效果类似。完全隐藏，因为时间问题，不会去处理。该issues关闭
