### ISSUE TITLE
可不可能支持群聊呢？

### ISSUE THREAD

**Issue by XTsat** [Mingyueyixi/MaskWechat#29]
有些群聊也想要隐藏掉，现在只能对聊天生效

**Comment by Mingyueyixi** [comment]
本来就是支持隐藏掉群聊，不止群聊，微信运动、公众号啥的找到id也是隐藏的。如果你的不支持，就是说明你的有问题。不是版本就是环境一类的。

**Comment by XTsat** [comment]
找到原因了，折叠的群聊不能隐藏，取消折叠就可以了
