### ISSUE TITLE
1.3版本bug反馈

### ISSUE THREAD

**Issue by chankam1024** [Mingyueyixi/MaskWechat#3]
机型：红米K50 Pro MIUI14
微信版本：8.0.32
复现步骤：添加配置→跳转微信首页→提示点击用户对话框→确定→随便点用户对话框→弹出编辑配置框→确定。

按理说就配置好了，但是每次点击该用户对话框时，都还是会弹出编辑配置框，点确认退出弹框，再次点击用户对话框还是会弹编辑配置框，无限循环，除非点击退出配置。其他功能正常。

**Comment by dreamwining** [comment]
作者加个微信吧，我做Java开发的，可以帮助测试。
微信：cdream1024

**Comment by Mingyueyixi** [comment]
> 机型：红米K50 Pro MIUI14 微信版本：8.0.32 复现步骤：添加配置→跳转微信首页→提示点击用户对话框→确定→随便点用户对话框→弹出编辑配置框→确定。
> 
> 按理说就配置好了，但是每次点击该用户对话框时，都还是会弹出编辑配置框，点确认退出弹框，再次点击用户对话框还是会弹编辑配置框，无限循环，除非点击退出配置。其他功能正常。

应该是正常现象，这个我一开始留下的，方便不停抓取。看后续使用情况，觉得奇怪的人比较多，会重新搞
