### ISSUE TITLE
1.3新春版聊天记录隐藏问题

### ISSUE THREAD

**Issue by ZIKHOY** [Mingyueyixi/MaskWechat#4]
隐藏了聊天记录后，在主页消息列表仍然可以看见最后一条聊天记录

**Comment by Mingyueyixi** [comment]
> 隐藏了聊天记录后，在主页消息列表仍然可以看见最后一条聊天记录

这是未实现的功能。

**Comment by Mingyueyixi** [comment]
close reason: 
v1.4春节肥三斤版本初步实现
