### ISSUE TITLE
请问隐藏图标功能正常吗？

### ISSUE THREAD

**Issue by F122Y** [Mingyueyixi/MaskWechat#40]
目前隐藏内容功能正常，但是隐藏图标好像并没有生效，请问这个功能是正常的吗？还是需要如何设置？
微信版本：8.0.37（插件详情内下载）
maskwechat：v1.19
![Screenshot_20231030-204255](https://github.com/Mingyueyixi/MaskWechat/assets/30532643/fac729f9-2fd6-483f-b023-76ad5414bccb)

**Comment by Mingyueyixi** [comment]
隐藏图标不是隐藏微信图标，而是隐藏糊脸的图标。如果你要隐藏微信的图标，可以试试其他模块，或者手机自带的私密空间隐藏

**Comment by F122Y** [comment]
> 隐藏图标不是隐藏微信图标，而是隐藏糊脸的图标。如果你要隐藏微信的图标，可以试试其他模块，或者手机自带的私密空间隐藏

哦，就是不在菜单页面展示maskwechat的图标是吧？我还以为自带隐藏微信app的图标功能

**Comment by Mingyueyixi** [comment]
当然了。微信又没有隐藏的必要。反倒模块app有可能被当场抓获

**Comment by Mingyueyixi** [comment]
你可以用隐秘空间模块。自己实现也行，稳定性差点，因为安卓10开始，不许应用动态隐藏图标

**Comment by F122Y** [comment]
是的，我刚才下载了隐秘空间模块，满足了我的需求~自己实现就没有这个技术了，感谢你们开发者的无私奉献。Salute🫡
