### ISSUE TITLE
重大bug反馈，列表视图消息显露

### ISSUE THREAD

**Issue by LHC12580** [Mingyueyixi/MaskWechat#43]
尊敬的开发者同志，现在有一个bug，视图是可以隐藏的，但是！聊天页面会出现消息露图，露消息，点开密友是隐藏的，什么都没有！但是问题就是聊天列表界面上！会出现之前发出的消息文字！![IMG_20240212_165238_1.jpg](https://github.com/Mingyueyixi/MaskWechat/assets/133021043/e3f58aac-ce9d-424a-9592-23b81d9efa1c)

希望可以改进！这个比 通知消息泄露还严重！

**Comment by Mingyueyixi** [comment]
你用的大概念是未适配的版本。这里的隐藏不怎么通用，基本上版本对不上就失效

**Comment by LHC12580** [comment]
8.33的麻烦更新一下，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月12日(周一) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mingyueyixi/MaskWechat] 重大bug反馈，列表视图消息显露 (Issue #43)




 
你用的大概念是未适配的版本。这里的隐藏不怎么通用，基本上版本对不上就失效

**Comment by LHC12580** [comment]
已经升级到8.33了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月16日(周五) 晚上11:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mingyueyixi/MaskWechat] 重大bug反馈，列表视图消息显露 (Issue #43)




 
你的版本太落后了，属于一开始就不兼容的版本，代马很乱，不改了。建议升级

**Comment by Mingyueyixi** [comment]
太落后了，33版都不一定支持隐藏最后一条消息。用旧版的话，自己看更新日志，选个版本看是否支持

**Comment by LHC12580** [comment]
因为要使用xposed模块，如果微信更新太快，微信最新版本都不支持了，还有些漏洞微信最新版本会修复，太难啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月17日(周六) 下午3:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mingyueyixi/MaskWechat] 重大bug反馈，列表视图消息显露 (Issue #43)




 
太落后了，33版都不一定支持隐藏最后一条消息。用旧版的话，自己看更新日志，选个版本看是否支持

**Comment by Mingyueyixi** [comment]
微信半月到一个月一个更新

**Comment by LHC12580** [comment]
😹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月2日(周六) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mingyueyixi/MaskWechat] 重大bug反馈，列表视图消息显露 (Issue #43)




 
Closed #43 as completed.

**Comment by Mingyueyixi** [comment]
关了关了。换版本

**Comment by LHC12580** [comment]
其他插卡xposed不支持最新微信版本，漏洞会被修复，只能用低版本微信



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月3日(周日) 凌晨1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mingyueyixi/MaskWechat] 重大bug反馈，列表视图消息显露 (Issue #43)




 
关了关了。换版本
