### ISSUE TITLE
搜索和查找聊天记录问题

### ISSUE THREAD

**Issue by zhentouyu** [Mingyueyixi/MaskWechat#44]
某个配置的糊脸ID设置成数字时，微信主页最上面的搜索里一旦输入内容就会闪退
无论什么时候，查找聊天记录中的图片和视频都没有显示

**Comment by Mingyueyixi** [comment]
附上你的微信版本号、log、以及模块版本号。最新版本对搜索作了遍历内存暴力隐藏，没有log是无法排查的

**Comment by zhentouyu** [comment]
微信8.0.47
模块版本v2.0-test-release
[LSPosed_2024-02-21T17_47_53.277995.zip](https://github.com/Mingyueyixi/MaskWechat/files/14357668/LSPosed_2024-02-21T17_47_53.277995.zip)

**Comment by Mingyueyixi** [comment]
![image](https://github.com/Mingyueyixi/MaskWechat/assets/19200895/b6343726-871b-4910-9cfe-5faf9614cd82)

原因不是很明确，你可以尝试吧这行代码去掉看看。

**Comment by Mingyueyixi** [comment]
2.1已修复
