### ISSUE TITLE
微信内搜索好友时微信闪退

### ISSUE THREAD

**Issue by cheng4217le** [Mingyueyixi/MaskWechat#47]
新版使用时，在微信搜索框里搜好友时微信闪退，微信版本8.0.47，糊脸装的2.1，目前安装还有一个微X模块（2.44_5.41），其他就没有相关的了。1.9元夕版搜索好友不闪退

**Comment by Mingyueyixi** [comment]
> 新版使用时，在微信搜索框里搜好友时微信闪退，微信版本8.0.47，糊脸装的2.1，目前安装还有一个微X模块（2.44_5.41），其他就没有相关的了。1.9元夕版搜索好友不闪退

装最新版，你需要去关闭暴力隐藏

**Comment by Mingyueyixi** [comment]
暴力适配的瓜，此功能不稳定，无法适配，已移除。v2.2版开始，改为hook数据库
