### ISSUE TITLE
最新版隐藏了好友列表，但搜聊天关键字还是会出现

### ISSUE THREAD

**Issue by 94MJ** [Mingyueyixi/MaskWechat#53]
好友列表搜不到这个人，但跟这个人的聊天记录的关键字，在搜索栏里搜的时候，也还是会出现这个人，还是容易被查到

**Comment by 94MJ** [comment]
新发现bug，群聊点右上角3个点微信会闪退重启

**Comment by 94MJ** [comment]
新发现bug，我还装了个微x，群 聊右上角三个点，点了会卡1，2秒，然后闪退重启

**Comment by Mingyueyixi** [comment]
新方式sql未没隐藏聊天记录搜索，已修

**Comment by 94MJ** [comment]
> 新方式sql未没隐藏聊天记录搜索，已修

修好了吗，好像还没看到推送更新耶

**Comment by Mingyueyixi** [comment]
> > 新方式sql未没隐藏聊天记录搜索，已修
> 
> 修好了吗，好像还没看到推送更新耶

修了。但不确定有没有其他问题。所以后面再推。修复版你可以在action或tg群拿
