### ISSUE TITLE
由MaskWechat造成的微信朋友圈闪退问题

### ISSUE THREAD

**Issue by xiaoye-kotlin** [Mingyueyixi/MaskWechat#54]
我很遗憾的告诉作者这件事，今天当我更新了MaskWechat并重启微信后发现一进入朋友圈就闪退，当我关闭MaskWechat排查原因时，朋友圈又能够正常地进入，我的微信只有两个模块进行修改，一个是MaskWechat另一个是微X模块，希望作者能尽快找到闪退原因并修复，我的微信版本是8.0.48。

**Comment by Mingyueyixi** [comment]
已于2.3版本修复。

**Comment by xiaoye-kotlin** [comment]
好的，期待您的2.3版本

**Comment by Mingyueyixi** [comment]
2.3已经编译，只是在观察几天有没有别的反馈，没有才挂出去。现在可以在github action或去tg群下载。

**Comment by xiaoye-kotlin** [comment]
好的，我已经下载安装了，现在确实没有问题了，谢谢你。
