### ISSUE TITLE
请问是不是不支持非root使用npatch/onpatch打包？

### ISSUE THREAD

**Issue by zeemars** [Mingyueyixi/MaskWechat#64]
请问是不是不支持非root使用npatch/onpatch打包？
我自己测试，onpatch打包后，改了个微信的包名，进去后没效果。

**Comment by Mingyueyixi** [comment]
支持非root，并没有hook系统。但显示是未鸡活。具体不能用的原因，你得看log

**Comment by zeemars** [comment]
> 支持非root，并没有hook系统。但显示是未鸡活。具体不能用的原因，你得看log

我明白了，是因为我为了双开把微信的包名改掉了，所以hook不到。谢谢

**Comment by Mingyueyixi** [comment]
呃这，你玩得太野了，糊脸入口也有代马拦截包名，你自己改了编译
